"use client";

import React, { useState, useContext } from "react";
import { toast } from "react-toastify";
import CarouselDTO from "../dto/CarouselDTO";
import { LoginContext } from "@/module/context/LoginProvider";
import LoginContextType from "@/module/context/LoginContextType";

interface ModalCarouselProps {
  isOpen: boolean;
  onClose: () => void;
  onAddItem: (newItem: CarouselDTO, file: File, token: string) => void;
}

const ModalCarousel: React.FC<ModalCarouselProps> = ({
  isOpen,
  onClose,
  onAddItem,
}) => {
  const [file, setFile] = useState<File | null>(null);
  const { user } = useContext(LoginContext) as LoginContextType;

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
  
    if (!file) {
      toast.error("Please select a file.");
      return;
    }
  
    const newItem: CarouselDTO = {
      code: "", // Valoare temporară până când backend-ul o generează
      fileUrl: "", // File URL will be generated by the backend
      type: file.type.includes("image") ? "image" : "video",
    };
  
    onAddItem(newItem, file,user.token);
    setFile(null);
    onClose();
  };
  

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-lg p-6 w-full max-w-md">
        <h2 className="text-xl font-bold mb-4">Add Carousel Item</h2>
        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700">
              Upload File
            </label>
            <input
              type="file"
              onChange={handleFileChange}
              className="mt-1 block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer focus:outline-none"
              accept="image/*,video/*"
              required
            />
          </div>
          <div className="flex justify-end space-x-4">
            <button
              type="button"
              onClick={onClose}
              className="bg-gray-500 text-white px-4 py-2 rounded-md hover:bg-gray-600"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600"
            >
              Add Item
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ModalCarousel;
